### ISSUE TITLE
Error generating png

### ISSUE THREAD

**Issue by ANGEL-D-SAMUEL** [peterlionelnewman/czi2png#1]
![Screenshot from 2024-12-18 16-01-56](https://github.com/user-attachments/assets/52f9d54e-ea7a-4c75-bd38-c50ca769b8cf)

I am facing this issue, Can anyone please help me in this?

**Comment by peterlionelnewman** [comment]
Hi Angel,

I've updated the main file to print out the entire error properly:
```
...
    except Exception as e:
        print(f'failed to process {path}')
        print(f'Error: {str(e)}')
        tk.messagebox.showerror('Python Error',
            f'Failed to process file:\n{str(e)}\n\n'
            'Check pyconsole for more information.\n'
            'Might have something to do with multiprocessing an overallocation of memory.')
        return
```

If you update your main then run this I might be able to get a better idea of whats happened.

**Comment by ANGEL-D-SAMUEL** [comment]
![Screenshot from 2024-12-19 11-12-58](https://github.com/user-attachments/assets/e75730a2-f802-4cbf-a104-95dcd3905c9a)
This is the error it shows, after using updated main.py file

**Comment by ANGEL-D-SAMUEL** [comment]
Hi Peter,

This is the shape of my image
![Screenshot from 2024-12-19 11-36-09](https://github.com/user-attachments/assets/50f0fd41-7c92-4dad-9eee-567265a8b832)


In my slide, i have two tissues side by side normal on the left and tumor on the right side of same slide.
Will this cause any trouble when i need to convert from CZI to PNG? 
Also, my files are in different storage location connected to my linux server. Is there any requirement for the files to be there locally to perform this?

**Comment by peterlionelnewman** [comment]
G'day, 

Tough pickle to try work out whats happening with this limited error.

Seems like the images you've taken might not have a Z dimension, or there is a unexpected dimension order. You're shape is (2, 1, 53000, 166000, 3) -> (images, z, y, x, color)? Do you know the dimensions of the image? The images are really big, this doesnt appear to be confocal or brightfield data, is this taken as a tile from a slide scanner or something?

**Comment by peterlionelnewman** [comment]
Otherwise, I might suggest using IMageJ/Fiji. Alternatively if python scripting is important to you - then the AICS package that this GUI wraps has now all be superseded by bioio (which is being built out and is still maintained) - https://github.com/bioio-devs/bioio.

**Comment by ANGEL-D-SAMUEL** [comment]
Thank you Peter for looking into the issue. 👍🏼 I know its bit complicated.
